(set-option :smt.mbqi true)
(set-logic QF_LRA)
(declare-const hair Bool)
(declare-const feathers Bool)
(declare-const eggs Bool)
(declare-const milk Bool)
(declare-const airborne Bool)
(declare-const aquatic Bool)
(declare-const predator Bool)
(declare-const toothed Bool)
(declare-const backbone Bool)
(declare-const breathes Bool)
(declare-const venomous Bool)
(declare-const fins Bool)
(declare-const legs Real)
(declare-const tail Bool)
(declare-const domestic Bool)
(declare-const catsize Bool)
(assert (=  (and true true (not breathes)) true) )
(push)
(assert (= hair false))
(assert (= feathers true))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne true))
(assert (= aquatic true))
(assert (= predator true))
(assert (= toothed false))
(assert (= backbone true))
(assert (= breathes true))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.25))
(assert (= tail true))
(assert (= domestic false))
(assert (= catsize false))
(check-sat)
(pop)
(push)
(assert (= hair false))
(assert (= feathers false))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne true))
(assert (= aquatic false))
(assert (= predator false))
(assert (= toothed false))
(assert (= backbone false))
(assert (= breathes true))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.75))
(assert (= tail false))
(assert (= domestic false))
(assert (= catsize false))
(check-sat)
(pop)
(push)
(assert (= hair false))
(assert (= feathers true))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne true))
(assert (= aquatic false))
(assert (= predator false))
(assert (= toothed false))
(assert (= backbone true))
(assert (= breathes true))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.25))
(assert (= tail true))
(assert (= domestic true))
(assert (= catsize false))
(check-sat)
(pop)
(push)
(assert (= hair false))
(assert (= feathers false))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne false))
(assert (= aquatic false))
(assert (= predator false))
(assert (= toothed false))
(assert (= backbone false))
(assert (= breathes true))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.75))
(assert (= tail false))
(assert (= domestic false))
(assert (= catsize false))
(check-sat)
(pop)
(push)
(assert (= hair false))
(assert (= feathers true))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne true))
(assert (= aquatic false))
(assert (= predator true))
(assert (= toothed false))
(assert (= backbone true))
(assert (= breathes true))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.25))
(assert (= tail true))
(assert (= domestic false))
(assert (= catsize false))
(check-sat)
(pop)
(push)
(assert (= hair false))
(assert (= feathers true))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne true))
(assert (= aquatic false))
(assert (= predator false))
(assert (= toothed false))
(assert (= backbone true))
(assert (= breathes true))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.25))
(assert (= tail true))
(assert (= domestic false))
(assert (= catsize true))
(check-sat)
(pop)
(push)
(assert (= hair false))
(assert (= feathers false))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne false))
(assert (= aquatic true))
(assert (= predator true))
(assert (= toothed true))
(assert (= backbone true))
(assert (= breathes false))
(assert (= venomous false))
(assert (= fins true))
(assert (= legs 0.0))
(assert (= tail true))
(assert (= domestic false))
(assert (= catsize false))
(check-sat)
(pop)
(push)
(assert (= hair true))
(assert (= feathers false))
(assert (= eggs false))
(assert (= milk true))
(assert (= airborne true))
(assert (= aquatic false))
(assert (= predator false))
(assert (= toothed true))
(assert (= backbone true))
(assert (= breathes true))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.25))
(assert (= tail true))
(assert (= domestic false))
(assert (= catsize false))
(check-sat)
(pop)
(push)
(assert (= hair true))
(assert (= feathers false))
(assert (= eggs false))
(assert (= milk true))
(assert (= airborne false))
(assert (= aquatic false))
(assert (= predator false))
(assert (= toothed true))
(assert (= backbone true))
(assert (= breathes true))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.5))
(assert (= tail true))
(assert (= domestic false))
(assert (= catsize true))
(check-sat)
(pop)
(push)
(assert (= hair false))
(assert (= feathers false))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne false))
(assert (= aquatic false))
(assert (= predator true))
(assert (= toothed false))
(assert (= backbone false))
(assert (= breathes false))
(assert (= venomous false))
(assert (= fins false))
(assert (= legs 0.0))
(assert (= tail false))
(assert (= domestic false))
(assert (= catsize false))
(check-sat)
(pop)
(push)
(assert (= hair false))
(assert (= feathers false))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne false))
(assert (= aquatic true))
(assert (= predator true))
(assert (= toothed true))
(assert (= backbone true))
(assert (= breathes false))
(assert (= venomous false))
(assert (= fins true))
(assert (= legs 0.0))
(assert (= tail true))
(assert (= domestic false))
(assert (= catsize true))
(check-sat)
(pop)
