(set-option :smt.mbqi true)
(set-logic QF_LRA)
(declare-const hair Bool)
(declare-const feathers Bool)
(declare-const eggs Bool)
(declare-const milk Bool)
(declare-const airborne Bool)
(declare-const aquatic Bool)
(declare-const predator Bool)
(declare-const toothed Bool)
(declare-const backbone Bool)
(declare-const breathes Bool)
(declare-const venomous Bool)
(declare-const fins Bool)
(declare-const legs Real)
(declare-const tail Bool)
(declare-const domestic Bool)
(declare-const catsize Bool)
(assert (= hair false))
(assert (= feathers false))
(assert (= eggs true))
(assert (= milk false))
(assert (= airborne false))
(assert (= aquatic true))
(assert (= predator true))
(assert (= toothed true))
(assert (= backbone true))
(assert (= breathes false))
(assert (= venomous false))
(assert (= fins true))
(assert (= legs 0.0))
(assert (= tail true))
(assert (= domestic false))
(assert (= catsize true))
(check-sat)
(eval  (and hair milk toothed backbone breathes tail (not feathers) (not eggs) (not aquatic) (not predator) (not venomous) (not fins) (not domestic) (or (and airborne (= legs (/ 1 4)) (not catsize)) (and catsize (not airborne) (= legs (/ 1 2))))))
