(set-option :smt.mbqi true)
(declare-const sepal_length Int)
(declare-const petal_length Int)
(declare-const sepal_width Int)
(declare-const petal_width Int)
(assert (= sepal_length 5))
(assert (= petal_length 5))
(assert (= sepal_width 5))
(assert (= petal_width 5))
(check-sat)
(eval   (ite (< petal_length 5) (ite (>= petal_length (/ 3 2)) (ite (= petal_length 4) (* (/ 1 4) petal_length) (ite (>= sepal_length 5) (ite (>= sepal_width (/ 5 2)) (ite (> petal_length (/ 3 2)) (ite (>= petal_length 2) (ite (<= sepal_width 3) (ite (>= sepal_length 6) (ite (< sepal_width 3) 1 0) (- sepal_width 2)) 1) 0) 0) (- petal_width (/ 1 2))) 0)) 0) (ite (>= sepal_width 3) (ite (<= sepal_length 6) 0 0) (ite (< sepal_width 3) 1 0))))